# Generated by Django 2.2.3 on 2019-07-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190728_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('STD', 'Student'), ('TCH', 'Teacher')], max_length=3),
        ),
    ]
