# Generated by Django 2.2.3 on 2019-07-30 11:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('date', models.DateField(default=datetime.datetime(2019, 7, 30, 11, 27, 32, 342160, tzinfo=utc))),
                ('details', models.TextField()),
                ('students_count', models.IntegerField(default=1)),
                ('students', models.ManyToManyField(limit_choices_to={'role': 'STD'}, related_name='students', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(default=1, limit_choices_to={'role': 'TCH'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
