# Generated by Django 2.2.3 on 2019-07-30 11:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 30, 11, 28, 11, 180282, tzinfo=utc)),
        ),
    ]
