# Generated by Django 2.2.3 on 2019-08-01 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_auto_20190731_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
